// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydhynlyafowbcrebafjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkaHlubHlhZm93YmNyZWJhZmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMTQxNzUsImV4cCI6MjA2MjU5MDE3NX0.czEEB4EA_SRWHnwf-oiQtDHby6HYzhL-NyNBslBkL-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);